service: aws-test

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: '20201221'
  region: ap-southeast-2

  environment:
    AMQP_URL: 'amqps://'
    POSTGRESQL_DB_URL: 'postgresql://'

functions:
  hello:
    handler: lambda.main
    timeout: 120
    events:
      - http:
          path: /
          method: post
          authorizer:
            type: TOKEN
            name: auth_func
            identitySource: method.request.header.Authorization
            resultTtlInSeconds: 0

  auth_func:
    handler: lambda.auth

plugins:
  - serverless-python-requirements

